name: Deploy Node.js App to Platformatic Cloud

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application project repository
        uses: actions/checkout@v3

      - name: Install project dependencies
        run: npm install

      - name: Deploy application to Platformatic Cloud
        uses: platformatic/onestep@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_ID }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_API_KEY }}
          platformatic_config_path: ./platformatic.db.json

      - name: Output the URL of the deployed application
        run: echo "Deployed app URL: ${{ steps.deploy.outputs.platformatic_app_url }}"
