name: Deploy Node.js App to Platformatic Cloud

on:
  push:
    branches:
      - main  # Assuming your main branch is named 'main'
  workflow_dispatch:
    inputs:
      label:
        description: "Preview Label"
        required: false
        default: ""

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --omit=dev

      - name: Deploy to Platformatic Cloud
        uses: platformatic/onestep@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_ID }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_API_KEY }}
          platformatic_config_path: ./platformatic.db.json
          post_pr_comment: true
          variables: custom_variable1, custom_variable2
          secrets: custom_secret1
          label: ${{ github.event.inputs.label }}
        env:
          plt_custom_variable: test1
          custom_variable1: test2
          custom_variable2: test3
          custom_secret1: test5

      - name: Output deployed app URL
        run: echo 'Deployed App URL: ${{ steps.deploy-app.outputs.platformatic_app_url }}'
