name: Deploy to Platformatic Cloud

on:
  push:
    branches:
      - main  # 或您想要自动部署的分支
  pull_request:
    branches:
      - main  # 根据需要可调整

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install

    - name: Deploy to Platformatic Cloud
      run: npx platformatic deploy -t dynamic --workspace-id ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_ID }} --workspace-key ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_API_KEY }} --label my-deploy-label
      env:
        PLATFORMATIC_WORKSPACE_ID: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_ID }}
        PLATFORMATIC_WORKSPACE_API_KEY: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_API_KEY }}
